# Generated by Django 4.1.4 on 2022-12-21 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_homework_date_now_homework_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date_now',
        ),
        migrations.AddField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
